<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\View\Admin\Form\Field;

/**
 * Class Text
 * @package B2W\SkyHub\View\Admin\Form\Field
 */
class Text extends FieldAbstract
{
    /**
     * @var string
     */
    protected $_template = 'admin/attribute/field/text.php';
}
