<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Entity;

/**
 * Class CategoryEntity
 * @package B2W\SkyHub\Model\Entity
 */
class CategoryEntity extends EntityAbstract implements \B2W\SkyHub\Contract\Entity\CategoryEntityInterface
{
    protected $_id     = null;
    protected $_code   = null;
    protected $_name   = null;
    protected $_parent = null;

    /**
     * @return null
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * @param $id
     * @return $this|mixed
     */
    public function setId($id)
    {
        $this->_id = $id;
        return $this;
    }

    /**
     * @return null
     */
    public function getCode()
    {
        return $this->_code;
    }

    /**
     * @param $code
     * @return $this|mixed
     */
    public function setCode($code)
    {
        $this->_code = $code;
        return $this;
    }

    /**
     * @return null
     */
    public function getName()
    {
        return $this->_name;
    }

    /**
     * @param $name
     * @return $this|mixed
     */
    public function setName($name)
    {
        $this->_name = $name;
        return $this;
    }

    /**
     * @return mixed|null
     */
    public function getParent()
    {
        return $this->_parent;
    }

    /**
     * @param \B2W\SkyHub\Contract\Entity\CategoryEntityInterface $category
     * @return $this|mixed
     */
    public function setParent(\B2W\SkyHub\Contract\Entity\CategoryEntityInterface $category)
    {
        $this->_parent = $category;
        return $this;
    }
}
