<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contract\Repository\Product;

/**
 * Interface VariationRepositoryInterface
 * @package B2W\SkyHub\Contract\Repository\Product
 */
interface VariationRepositoryInterface
{
    /**
     * @param \B2W\SkyHub\Contract\Entity\ProductEntityInterface|\WP_Post $product
     * @return mixed
     */
    public function load($product);

    /**
     * @param $id
     * @return mixed
     */
    public function one($id);

    /**
     * @param $sku
     * @return mixed
     */
    public function sku($sku);
}
