<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Entity\Product\Attribute;

use B2W\SkyHub\Model\Entity\EntityAbstract;

/**
 * Class OptionEntity
 * @package B2W\SkyHub\Model\Entity\Product\Attribute
 */
class OptionEntity extends EntityAbstract implements \B2W\SkyHub\Contract\Entity\Product\Attribute\OptionEntityInterface
{
    /** @var int */
    protected $_id;
    /** @var string */
    protected $_code;
    /** @var string */
    protected $_label;

    /**
     * @return int
     */
    public function getId()
    {
        return $this->_id;
    }

    /**
     * @param $id
     * @return $this|mixed
     */
    public function setId($id)
    {
        $this->_id = $id;
        return $this;
    }

    /**
     * @return string
     */
    public function getCode()
    {
        return $this->_code;
    }

    /**
     * @param $code
     * @return $this|mixed
     */
    public function setCode($code)
    {
        $this->_code = $code;
        return $this;
    }

    /**
     * @return string
     */
    public function getLabel()
    {
        return $this->_label;
    }

    /**
     * @param $label
     * @return $this|mixed
     */
    public function setLabel($label)
    {
        $this->_label = $label;
        return $this;
    }
}
