<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Order\Item\Misc;

use B2W\SkyHub\Model\Entity\Order\ItemEntity;
use B2W\SkyHub\Model\Transformer\EntityToDbAbstract;

/** @method ItemEntity getEntity() */
class VariationId extends EntityToDbAbstract
{
    /**
     * @return mixed|null
     */
    protected function _getMapInstance()
    {
        return null;
    }

    /**
     * @return \B2W\SkyHub\Model\Transformer\Handler\Post|null
     * @throws \B2W\SkyHub\Exception\Data\RepositoryNotFound
     */
    public function convert()
    {
        $variation = \App::repository(\App::REPOSITORY_PRODUCT_VARIATION)->sku($this->getEntity()->getId());

        if ($variation->getId()) {
            return $variation->getId();
        }

        return null;
    }
}
