<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Order\Payment\Sefaz;

use B2W\SkyHub\Model\Entity\Order\Payment\SefazEntity;
use B2W\SkyHub\Model\Map\MapAttribute;
use B2W\SkyHub\Model\Map\Order\Payment\SefazMap;
use B2W\SkyHub\Model\Transformer\ApiToEntityAbstract;

/**
 * Class ApiToEntity
 * @package B2W\SkyHub\Model\Transformer\Order\Payment\Sefaz
 */
class ApiToEntity extends ApiToEntityAbstract
{
    /**
     * @return SefazEntity|mixed
     */
    protected function _getEntityInstance()
    {
        return new SefazEntity();
    }

    /**
     * @return SefazMap|mixed
     */
    protected function _getMapInstance()
    {
        return new SefazMap();
    }
}
