<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

return Array(
    'url' => Array(
        'skyhub'    => 'url',
        'wordpress' => '_skyhub_order_shipping_url'
    ),
    'method' => Array(
        'skyhub'    => 'method',
        'wordpress' => '_skyhub_order_shipping_method'
    ),
    'code' => Array(
        'skyhub'    => 'code',
        'wordpress' => '_skyhub_order_shipping_code'
    ),
    'carrier' => Array(
        'skyhub'    => 'carrier',
        'wordpress' => '_skyhub_order_shipping_carrier'
    )
);