<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */
namespace B2W\SkyHub\Model\Map\Order\Shipment;

use B2W\SkyHub\Model\Map\MapAbstract;

class TrackMap extends MapAbstract
{
    /**
     * @return string
     */
    protected function _getConfigPath()
    {
        return 'map/order/shipments/tracks';
    }

    /**
     * @return null|string
     */
    protected function _getOptionsName()
    {
        return null;
    }
}