<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Helper;


use B2W\SkyHub\Contract\Entity\OrderEntityInterface;

/**
 * Class Order
 * @package B2W\SkyHub\Helper
 */
class Order
{
    /**
     * @param OrderEntityInterface $order
     * @return bool
     */
    public function isComplete(OrderEntityInterface $order)
    {
        /** TODO improve complete check */
        return $order->getStatus()->getCode() == 'wc-completed';
    }
}
