<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Product;

use B2W\SkyHub\Model\Entity\ProductEntity;
use B2W\SkyHub\Model\Map\ProductMap;
use B2W\SkyHub\Model\Transformer\DbToEntityAbstract;

/**
 * Class DbToEntity
 * @package B2W\SkyHub\Model\Transformer\Product
 */
class DbToEntity extends DbToEntityAbstract
{
    /**
     * @return ProductEntity|null
     */
    protected function _getEntityInstance()
    {
        return new ProductEntity();
    }

    /**
     * @return array|mixed
     */
    protected function _getAttributeMap()
    {
        $map = new ProductMap();
        return $map->map();
    }
}
