<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Order\Status;

use B2W\SkyHub\Model\Entity\Order\StatusEntity;
use B2W\SkyHub\Model\Transformer\DbToEntityAbstract;

/**
 * Class DbToEntity
 * @package B2W\SkyHub\Model\Transformer\Order\Item
 */
class DbToEntity extends DbToEntityAbstract
{
    /**
     * @return StatusEntity|null
     */
    protected function _getEntityInstance()
    {
        return new StatusEntity();
    }

    /**
     * @return array|mixed
     */
    protected function _getAttributeMap()
    {
        return array();
    }

    /**
     * @return StatusEntity
     */
    public function convert()
    {
        $status = new StatusEntity();
        $status->setType('');
        $status->setCode($this->_post->post_status);
        $status->setLabel($this->_post->post_status);

        return $status;
    }
}
