<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

namespace B2W\SkyHub\Model\Cron\Product;

use B2W\SkyHub\Model\Cron\Jobs;
use B2W\SkyHub\Model\Queue;
use B2W\SkyHub\Exception\Exception;

class Integration extends Jobs
{
    /**
     * Execute queue
     *
     * @return Bollean
     */
    public function execute()
    {
        try{
            $queue = new Queue();
            $queue->run(self::TYPE_QUEUE_PRODUCT);
        } catch (Exception $e) {
            return false;
        }
    }
}