<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */
namespace B2W\SkyHub\View\Admin\Queue\Integration\SkyHub;

use B2W\SkyHub\View\Template;

class Page extends Template
{
    protected $_template = 'admin/queue/grid.php';

    /**
     * Table with data of queue
     *
     * @return void
     */
    public function table()
    {
        if (!class_exists('WP_List_Table')) {
            require_once(ABSPATH . 'wp-admin' . DS . 'includes' . DS . 'class-wp-list-table.php');
        }

        $table = new \B2W\SkyHub\View\Admin\Queue\Integration\SkyHub\Grid();
        $table->prepare_items();
        $table->display();
    }
}
