<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contract\Entity\Order;

/**
 * Interface StatusEntityInterface
 * @package B2W\SkyHub\Contract\Entity\Order
 */
interface StatusEntityInterface
{
    /**
     * @return string
     */
    public function getCode();

    /**
     * @param $code
     * @return string
     */
    public function setCode($code);

    /**
     * @return string
     */
    public function getLabel();

    /**
     * @param $label
     * @return string
     */
    public function setLabel($label);

    /**
     * @return string
     */
    public function getType();

    /**
     * @param $type
     * @return string
     */
    public function setType($type);
}
