<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Order\Payment;

use B2W\SkyHub\Model\Entity\Order\PaymentEntity;
use B2W\SkyHub\Model\Map\MapAttribute;
use B2W\SkyHub\Model\Map\Order\PaymentMap;
use B2W\SkyHub\Model\Transformer\ApiToEntityAbstract;

/**
 * Class ApiToEntity
 * @package B2W\SkyHub\Model\Transformer\Order\Payment
 */
class ApiToEntity extends ApiToEntityAbstract
{
    /**
     * @return PaymentEntity|mixed
     */
    protected function _getEntityInstance()
    {
        return new PaymentEntity();
    }

    /**
     * @return PaymentMap|mixed
     */
    protected function _getMapInstance()
    {
        return new PaymentMap();
    }

    /**
     * @param null $data
     * @return array
     */
    protected function _prepareData($data = null)
    {
        $data = current($this->_response);
        return parent::_prepareData($data);
    }
}
