<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2019 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Tiago Tescaro <tiago.tescaro@b2wdigital.com>
 */

namespace B2W\SkyHub\Model\Transformer\Order\Shipment;

use B2W\SkyHub\Model\Entity\Order\ShipmentEntity;
use B2W\SkyHub\Model\Map\Order\ShipmentMap;

class ApiToEntity extends \B2W\SkyHub\Model\Transformer\ApiToEntityAbstract
{
    /**
     * @return ShipmentEntity
     */
    protected function _getEntityInstance()
    {
        return new ShipmentEntity();
    }

    /**
     * @return ShipmentMap
     */
    protected function _getMapInstance()
    {
        return new ShipmentMap();
    }

    /**
     * Prepare data
     * 
     * @param Array|Null $data
     * @return Array
     */
    protected function _prepareData($data = null)
    {
        $data = $data ? current($data) : current($this->_response);
        return parent::_prepareData($data);
    }
}
