<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Model\Transformer\Customer;

use B2W\SkyHub\Model\Entity\CustomerEntity;
use B2W\SkyHub\Model\Map\CustomerMap;
use B2W\SkyHub\Model\Transformer\DbToEntityAbstract;

/**
 * Class DbToEntity
 * @package B2W\SkyHub\Model\Transformer\Customer
 */
class DbToEntity extends DbToEntityAbstract
{
    /**
     * @return \B2W\SkyHub\Model\Map\MapAttributeCollection|mixed
     */
    protected function _getAttributeMap()
    {
        $map = new CustomerMap();
        return $map->map();
    }

    /**
     * @return CustomerEntity|null
     */
    public function _getEntityInstance()
    {
        return new CustomerEntity();
    }
}
