<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contract\Repository;

/**
 * Interface CategoryRepositoryInterface
 * @package B2W\SkyHub\Contract\Repository
 */
interface CategoryRepositoryInterface
{
    /**
     * @param \B2W\SkyHub\Contract\Entity\ProductEntityInterface $product
     * @return mixed
     */
    public function load(\B2W\SkyHub\Contract\Entity\ProductEntityInterface $product);

    /**
     * @param $id
     * @return mixed
     */
    public function one($id);
}
