<?php
/**
 * BSeller - B2W Companhia Digital
 *
 * DISCLAIMER
 *
 * Do not edit this file if you want to update this module for future new versions.
 *
 * @copyright     Copyright (c) 2017 B2W Companhia Digital. (http://www.bseller.com.br/)
 * @author        Luiz Tucillo <luiz.tucillo@e-smart.com.br>
 */

namespace B2W\SkyHub\Contract\Repository;

use B2W\SkyHub\Contract\Entity\CustomerEntityInterface;

/**
 * Interface CustomerRepositoryInterface
 * @package B2W\SkyHub\Contract\Repository
 */
interface CustomerRepositoryInterface
{
    /**
     * @param \B2W\SkyHub\Contract\Entity\OrderEntityInterface|\WP_Post $order
     * @return CustomerEntityInterface
     */
    public function load($order);

    /**
     * @param $cpf
     * @return CustomerEntityInterface
     */
    public function cpf($cpf);

    /**
     * @param $cnpj
     * @return CustomerEntityInterface
     */
    public function cnpj($cnpj);

    /**
     * @param integer
     * @return CustomerEntityInterface
     */
    public function one($id);
}
